apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: app-of-apps 
spec: 
  destination: 
    server: https://kubernetes.default.svc 
    namespace: argocd 
  source: 
    repoURL: 'https://github.com/sesantama/tfg-monolit2microservices.git'
    path: 'microservices/kubernetes_cluster_app/helm/mediawiki' 
    targetRevision: HEAD 
  project: default
