apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-database: {{ .Values.mysql.database }}
  mysql-user: {{ .Values.mysql.user  }}
  mysql-root-password: {{ .Values.mysql.rootPassword }}
  mysql-password: {{ .Values.mysql.password }}
