# -*- mode: ruby -*-
# vi: set ft=ruby :
##Las mv de vagrant el usuario es:
#vagrant
#vagrant
#root
#vagrant
Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-8"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook_centos_install_docker.yaml"
	 config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "2048"
	 vb.cpus = "2"
 end 

  # appmaster
    config.vm.define "appmaster" do |app|
    app.vm.hostname = "appmaster"
    app.vm.network "private_network", ip: "10.0.0.20"
    #app.vm.provision "shell", path: "provision/provision-for-balancer.sh"
	end

  # appworker1
    config.vm.define "appworker1" do |app|
    app.vm.hostname = "appworker1"
    app.vm.network "private_network", ip: "10.0.0.21"
	#app.vm.provision "shell", path: "provision/provision-for-nginx.sh"
	end
	
	# appworker2
    config.vm.define "appworker2" do |app|
    app.vm.hostname = "appworker2"
    app.vm.network "private_network", ip: "10.0.0.22"
	#app.vm.provision "shell", path: "provision/provision-for-nginx.sh"
  end
end
end
