apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: apache
        image: {{ .Values.apache.image }}
        ports:
        - containerPort: {{ .Values.apache.port }}