apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Chart.Name }}
    component: apache
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: apache
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: apache
    spec:
      containers:
      - name: apache
        image: {{ .Values.apache.image }}
        ports:
        - containerPort: {{ .Values.apache.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Chart.Name }}
    component: mysql
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: mysql
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: rootPassword
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: userPassword
        ports:
        - containerPort: {{ .Values.mysql.port }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app: {{ .Chart.Name }}
    component: php
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: php
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: php
    spec:
      containers:
      - name: php
        image: {{ .Values.php.image }}
        ports:
        - containerPort: {{ .Values.php.port }}
        env:
        - name: PHP_MEMORY_LIMIT
          value: "{{ .Values.php.memoryLimit }}"
        - name: PHP_MAX_EXECUTION_TIME
          value: "{{ .Values.php.maxExecutionTime }}"
        volumeMounts:
        - name: php-data
          mountPath: /var/www/html
      volumes:
      - name: php-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-php-pvc
