apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:7.4-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /usr/local/etc/php
          name: php-config
      volumes:
      - name: php-config
        persistentVolumeClaim:
          claimName: php-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi