# PersistentVolume for MySQL
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: mysql
spec:
  capacity:
    storage: 10Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain  # What happens to the PV when the PVC is deleted
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  hostPath:
    path: /mnt/data/mysql  # Path on the node where data will be stored

---

# PersistentVolumeClaim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistentVolume.storageClass }}

# PersistentVolume for PHP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-php-pv
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: php
spec:
  capacity:
    storage: 5Gi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  hostPath:
    path: /mnt/data/php
---

# PersistentVolumeClaim for PHP
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-php-pvc
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.persistentVolume.storageClass }}