apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.apache.port }}
  selector:
    app: {{ .Chart.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: {{ .Chart.Name }}