---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-config
  namespace: {{ .Values.namespace }}
data:
  php.ini: |
    memory_limit = {{ .Values.php.memoryLimit }}
    max_execution_time = {{ .Values.php.maxExecutionTime }}
    upload_max_filesize = {{ .Values.php.uploadMaxFilesize }}
    post_max_size = {{ .Values.php.postMaxSize }}
    error_reporting = {{ .Values.php.iniSettings.error_reporting }}
    display_errors = {{ .Values.php.iniSettings.display_errors }}
    log_errors = {{ .Values.php.iniSettings.log_errors }}
    opcache_enable = {{ .Values.php.iniSettings.opcache_enable }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-fpm-config
  namespace: {{ .Values.namespace }}
data:
  www.conf: |
    [global]
    log_level = {{ .Values.php.fpmSettings.log_level }}
    [www]
    user = {{ .Values.php.fpmSettings.user }}
    group = {{ .Values.php.fpmSettings.group }}
    listen = 0.0.0.0:{{ .Values.php.port }}
    pm = {{ .Values.php.fpmSettings.pm }}
    pm.max_children = {{ .Values.php.fpmSettings.pm_max_children }}
    pm.start_servers = {{ .Values.php.fpmSettings.pm_start_servers }}
    pm.min_spare_servers = {{ .Values.php.fpmSettings.pm_min_spare_servers }}
    pm.max_spare_servers = {{ .Values.php.fpmSettings.pm_max_spare_servers }}
    pm.status_path = /status

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
  namespace: {{ .Values.namespace }}
data:
  my.cnf: |
    [mysqld]
    innodb_use_native_aio = {{ .Values.mysql.mycnfSettings.innodb_use_native_aio }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-apache-config
  namespace: {{ .Values.namespace }}
data:
  httpd.conf: |
    ServerName localhost
    ServerRoot "/usr/local/apache2"
    Listen 80
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    <IfModule !mpm_prefork_module>
    </IfModule>
    <IfModule mpm_prefork_module>
    </IfModule>
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so
    <IfModule unixd_module>
    User www-data
    Group www-data
    </IfModule>
    ServerAdmin you@example.com
    <Directory />
        AllowOverride none
        Require all denied
    </Directory>
    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>
    <Files ".ht*">
        Require all denied
    </Files>
    ErrorLog /proc/self/fd/2
    LogLevel warn
    <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common
        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>
        CustomLog /proc/self/fd/1 common
    </IfModule>
    <IfModule alias_module>
        ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"
    </IfModule>
    <IfModule cgid_module>
    </IfModule>
    <Directory "/usr/local/apache2/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
    </Directory>
    <IfModule headers_module>
        RequestHeader unset Proxy early
    </IfModule>
    <IfModule mime_module>
        TypesConfig conf/mime.types
        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
    </IfModule>
    <IfModule proxy_html_module>
    Include conf/extra/proxy-html.conf
    </IfModule>
    <VirtualHost *:80>
      ServerName localhost
      DocumentRoot /var/www/html
      <Directory /var/www/html>
        DirectoryIndex index.php
        Options +FollowSymLinks +Indexes
        AllowOverride All
        Require all granted
      </Directory>
      AddType application/x-httpd-php .php
      <FilesMatch \.php$>
        SetHandler "proxy:fcgi://{{ .Release.Name }}-php-service.{{ .Values.namespace }}:{{ .Values.php.port }}/"
      </FilesMatch>
    </VirtualHost>
    <IfModule ssl_module>
    SSLRandomSeed startup builtin
    SSLRandomSeed connect builtin
    </IfModule>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mediawiki-settings
  namespace: {{ .Values.namespace }}
data:
  LocalSettings.php: |
    <?php
    if ( !defined( 'MEDIAWIKI' ) ) {
      exit;
    }
    require_once "$IP/includes/PlatformSettings.php";
    $wgSitename = "Monolit2Microservices";
    $wgScriptPath = "";
    $wgServer = "http://localhost:{{ .Values.php.port }}";
    $wgResourceBasePath = $wgScriptPath;
    $wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];
    $wgEnableEmail = true;
    $wgEnableUserEmail = true; # UPO
    $wgEmergencyContact = "apache@🌻.invalid";
    $wgPasswordSender = "apache@🌻.invalid";
    $wgEnotifUserTalk = false; # UPO
    $wgEnotifWatchlist = false; # UPO
    $wgEmailAuthentication = true;
    $wgDBtype = "mysql";
    $wgDBserver = getenv('DB_SERVER');
    $wgDBname = getenv('MYSQL_DATABASE');
    $wgDBuser = getenv('MYSQL_USER');
    $wgDBpassword = getenv('MYSQL_PASSWORD');
    $wgDBprefix = "m2m";
    $wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
    $wgSharedTables[] = "actor";
    $wgMainCacheType = CACHE_ACCEL;
    $wgMemCachedServers = [];
    $wgEnableUploads = false;
    $wgUseInstantCommons = false;
    $wgPingback = true;
    $wgShellLocale = "C.utf8";
    $wgLanguageCode = "ca";
    $wgSecretKey = "a17ca47abb212640217484aaf33a574f3039f4ceaf30697bc4221b36b5ac8e34";
    $wgAuthenticationTokenVersion = "1";
    $wgUpgradeKey = "9ce92dbb5335dff5";
    $wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
    $wgRightsUrl = "https://www.gnu.org/copyleft/fdl.html";
    $wgRightsText = "GNU Free Documentation License 1.3 o posterior";
    $wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/gnu-fdl.png";
    $wgDiff3 = "/usr/bin/diff3";
    $wgGroupPermissions['*']['createaccount'] = false;
    $wgGroupPermissions['*']['edit'] = false;
    $wgGroupPermissions['*']['read'] = false;
    $wgDefaultSkin = "vector";
    wfLoadSkin( 'MonoBook' );
    wfLoadSkin( 'Timeless' );
    wfLoadSkin( 'Vector' );