apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    app: {{ .Chart.Name }}
    component: apache
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: apache
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: apache
    spec:
      containers:
      - name: apache
        image: {{ .Values.apache.image }}
        ports:
        - containerPort: {{ .Values.apache.port }}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-password
      volumeMounts:
      - name: apache-config
        mountPath: /etc/apache2/sites-enabled/mediawiki.conf
        subPath: mediawiki.conf
      - name: mediawiki-settings
        mountPath: /var/lib/mediawiki/LocalSettings.php
        subPath: LocalSettings.php
    volumes:
    - name: apache-config
      configMap:
        name: {{ .Release.Name }}-apache-config
    - name: mediawiki-settings
      configMap:
        name: {{ .Release.Name }}-mediawiki-settings


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Chart.Name }}
    component: mysql
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: mysql
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secrets
              key: mysql-password
        ports:
        - containerPort: {{ .Values.mysql.port }}
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        securityContext:
          runAsUser: 1000
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc
      - name: mysql-config
        configMap:
          name: {{ .Release.Name }}-mysql-config


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app: {{ .Chart.Name }}
    component: php
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: php
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: php
    spec:
      containers:
      - name: php
        image: {{ .Values.php.image }}
        ports:
        - containerPort: {{ .Values.php.port }}
        env:
        - name: PHP_MEMORY_LIMIT
          value: "{{ .Values.php.memoryLimit }}"
        - name: PHP_MAX_EXECUTION_TIME
          value: "{{ .Values.php.maxExecutionTime }}"
        volumeMounts:
        - name: php-data
          mountPath: /var/www/html
        securityContext:
          runAsUser: 1000
      volumes:
      - name: php-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-php-pvc
